name: CD - Deploy Frontend to AKS

on:
  # Called by the orchestrator
  workflow_call:
    inputs:
      product_api_ip:
        description: Product API URL (e.g., http://X.X.X.X:8000)
        required: true
        type: string
      order_api_ip:
        description: Order API URL (e.g., http://Y.Y.Y.Y:8001)
        required: true
        type: string
      # Optional overrides; fall back to secrets if omitted
      aks_cluster_name:
        required: false
        type: string
      aks_resource_group:
        required: false
        type: string
  # Optional manual run
  workflow_dispatch: {}

permissions:
  contents: read

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  K8S_NAMESPACE: ecommerce

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Derive ACR name
        run: echo "ACR_NAME=${ACR_LOGIN_SERVER%%.*}" >> $GITHUB_ENV

      # ✅ Context before kubectl
      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group "${{ inputs.aks_resource_group || secrets.AKS_RESOURCE_GROUP }}" \
            --name          "${{ inputs.aks_cluster_name   || secrets.AKS_CLUSTER_NAME }}" \
            --overwrite-existing
          kubectl cluster-info

      - name: Ensure namespace exists
        run: |
          kubectl get ns "$K8S_NAMESPACE" >/dev/null 2>&1 || kubectl create ns "$K8S_NAMESPACE"

      - name: Inject backend URLs into main.js
        run: |
          sed -i "s|_PRODUCT_API_URL_|${{ inputs.product_api_ip }}|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|${{ inputs.order_api_ip }}|g"   frontend/main.js

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      # ✅ Build & push :latest (CI also pushes :latest, but we rebuild after injection)
      - name: Build & Push frontend (:latest)
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend/
          docker push    ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Apply manifests
        run: kubectl apply -n "$K8S_NAMESPACE" -f k8s/frontend.yaml

      # ✅ Force pods to pull fresh :latest even if tag unchanged
      - name: Rollout restart frontend (pull latest)
        run: |
          kubectl -n "$K8S_NAMESPACE" rollout restart deploy/frontend
          kubectl -n "$K8S_NAMESPACE" rollout status  deploy/frontend --timeout=180s

      - name: Logout Azure
        if: always()
        run: az logout
